version: '3.8'

services:
  db:
    image: postgres:16.3 
    environment:
      POSTGRES_DB: backendtest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    networks:
      - bridge_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENVIRONMENT: "DEV"
      SECRET_KEY: "SUPER_SECRET_KEY"
      DEV_DATABASE_URI: "postgresql+psycopg2://postgres:12345678@db:5432/backendtest"  
      JWT_SECRET_KEY: "SUPER_SECRET_KEY"
      JWT_ALGORITHM: "RS256"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge
