version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENVIRONMENT: "DEV"
      SECRET_KEY: "SUPER_SECRET_KEY"
      DEV_DATABASE_URI: "postgresql+psycopg2://postgres:12345@db:5434/prueba"  # Keep connection details the same
      JWT_SECRET_KEY: "SUPER_SECRET_KEY"
      JWT_ALGORITHM: "RS256"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - mynetwork
  db:
    image: postgres:16.3  # Specify version here
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5434"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  mynetwork:
    driver: bridge


